version: "3.2"
services:
  backend:
    restart: always
    command : bash -c "python check_db.py --service-name db --ip db --port 3306 && 
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    
  frontend:
    restart: always
    command: npm start
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on: 
      - backend
