version: "3.2"
services:
  backend:
    restart: always
    command : bash -c "python manage.py collectstatic --no-input && gunicorn personal_site.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"