FROM node:14-alpine AS frontend-build

WORKDIR /app/frontend

COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g 
RUN npm install -g serve
COPY ./frontend ./

RUN npm run build

FROM python:3
ENV PYTHONUNBUFFERED 1
WORKDIR /app/backend
COPY ./backend/requirements.txt ./
RUN pip install -r requirements.txt
COPY ./backend .
COPY --from=frontend-build /app/frontend/build ./