version: "3.2"
services:
  backend:
    restart: always
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    
  frontend:
    restart: always
    command: npm start
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on: 
      - backend
