# Generated by Django 3.1.7 on 2021-04-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210322_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='detail_source',
        ),
    ]
