# Generated by Django 3.1.7 on 2021-09-03 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_webdevcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webdevcontact',
            old_name='business_description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='webdevcontact',
            old_name='project_description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='webdevcontact',
            name='work_type',
        ),
    ]
