# Generated by Django 3.1.7 on 2021-09-03 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210903_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdevcontact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
