# Generated by Django 3.1.7 on 2021-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slugified_title',
            field=models.SlugField(blank=True, max_length=510, unique=True),
        ),
    ]
