# Generated by Django 3.1.7 on 2021-03-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_slugified_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='slugified_title',
            new_name='slugified_name',
        ),
    ]
