# Generated by Django 3.1.7 on 2021-03-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210321_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='project',
            name='detail_source',
            field=models.FileField(blank=True, null=True, upload_to='project_detail_source'),
        ),
    ]
